In [44]:
import pandas as pd

In [56]:
df_Data = pd.read_csv(
    r"C:\$Data$\9. Prajakta Docs\Data Analyst-NumpyNinja\Machine Learning Jan22_2026\adult\adult - Data.csv",
    header=None,
    delim_whitespace=True
)

In [57]:
df_Test = pd.read_csv(
    r"C:\$Data$\9. Prajakta Docs\Data Analyst-NumpyNinja\Machine Learning Jan22_2026\adult\adult - Test.csv",
    header=None,
    delim_whitespace=True,
    skiprows=1   # adult.test has a header-like first line
)

In [58]:
df_Data.shape

(32561, 15)

In [59]:
df_Test.shape

(16281, 15)

In [60]:
df_Data.columns= ["age","workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain",
              "capital-loss","hours-per-week","native-country","income"]

In [61]:
df_Test.columns= ["age","workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain",
              "capital-loss","hours-per-week","native-country","income"]

In [62]:
df_Test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16281 entries, 0 to 16280
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             16281 non-null  object
 1   workclass       16281 non-null  object
 2   fnlwgt          16281 non-null  object
 3   education       16281 non-null  object
 4   education-num   16281 non-null  object
 5   marital-status  16281 non-null  object
 6   occupation      16281 non-null  object
 7   relationship    16281 non-null  object
 8   race            16281 non-null  object
 9   sex             16281 non-null  object
 10  capital-gain    16281 non-null  object
 11  capital-loss    16281 non-null  object
 12  hours-per-week  16281 non-null  object
 13  native-country  16281 non-null  object
 14  income          16281 non-null  object
dtypes: object(15)
memory usage: 1.9+ MB

In [63]:
df_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  object
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  object
 3   education       32561 non-null  object
 4   education-num   32561 non-null  object
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  object
 11  capital-loss    32561 non-null  object
 12  hours-per-week  32561 non-null  object
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: object(15)
memory usage: 3.7+ MB

In [64]:
combined= pd.concat([df_Data,df_Test],ignore_index=True)

In [65]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  object
 1   workclass       48842 non-null  object
 2   fnlwgt          48842 non-null  object
 3   education       48842 non-null  object
 4   education-num   48842 non-null  object
 5   marital-status  48842 non-null  object
 6   occupation      48842 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  object
 11  capital-loss    48842 non-null  object
 12  hours-per-week  48842 non-null  object
 13  native-country  48842 non-null  object
 14  income          48842 non-null  object
dtypes: object(15)
memory usage: 5.6+ MB

In [66]:
combined.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K

In [67]:
combined.shape

(48842, 15)

In [68]:
combined.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [72]:
combined.describe()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,48842,48842,48842,48842,48842,48842,48842,48842,48842,48842,48842,48842,48842,48842,48842
unique,74,9,28523,16,16,7,15,6,5,2,123,99,96,42,4
top,"36,","Private,","203488,","HS-grad,","9,","Married-civ-spouse,","Prof-specialty,","Husband,","White,","Male,","0,","0,","40,","United-States,",<=50K
freq,1348,33906,21,15784,15784,22379,6172,19716,41762,32650,44807,46560,22803,43832,24720